apiVersion: v1
kind: Pod
metadata:
  name: nginx-yaml
  labels:
    app: nginx
    tier: web
    environment: lab
spec:
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
